-- Create email_templates table for custom email template management
CREATE TABLE public.email_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  template_key TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  subject TEXT NOT NULL,
  html_content TEXT NOT NULL,
  available_variables JSONB DEFAULT '[]'::jsonb,
  is_customized BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.email_templates ENABLE ROW LEVEL SECURITY;

-- Only admins can manage email templates
CREATE POLICY "Admins can view email templates"
ON public.email_templates
FOR SELECT
USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can insert email templates"
ON public.email_templates
FOR INSERT
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can update email templates"
ON public.email_templates
FOR UPDATE
USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can delete email templates"
ON public.email_templates
FOR DELETE
USING (has_role(auth.uid(), 'admin'::app_role));

-- Insert default templates
INSERT INTO public.email_templates (template_key, name, subject, html_content, available_variables) VALUES
('approval_notification', 'Aprovação de Conta', '🎉 Sua conta foi aprovada - FurionPay', '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="text-align: center; margin-bottom: 30px;"><img src="{logoUrl}" alt="FurionPay" style="max-width: 200px; height: auto;"></div><div style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px;"><h1 style="margin: 0 0 10px 0; font-size: 28px;">✅ Conta Aprovada!</h1><p style="margin: 0; font-size: 16px; opacity: 0.9;">Bem-vindo à FurionPay</p></div><div style="background: #f9fafb; padding: 25px; border-radius: 10px; margin-bottom: 20px;"><p style="margin: 0 0 15px 0;">Olá <strong>{userName}</strong>,</p><p style="margin: 0 0 15px 0;">Sua conta foi aprovada com sucesso! Agora você tem acesso completo à plataforma FurionPay.</p><p style="margin: 0;">Acesse sua conta e comece a receber pagamentos via PIX de forma rápida e segura.</p></div><div style="text-align: center; padding: 20px;"><p style="color: #6b7280; font-size: 14px; margin: 0;">© 2024 FurionPay. Todos os direitos reservados.</p></div></body></html>', '["userName", "userEmail", "logoUrl"]'::jsonb),

('document_approved', 'Documentos Aprovados', '✅ Seus documentos foram aprovados - FurionPay', '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="text-align: center; margin-bottom: 30px;"><img src="{logoUrl}" alt="FurionPay" style="max-width: 200px; height: auto;"></div><div style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px;"><h1 style="margin: 0 0 10px 0; font-size: 28px;">✅ Documentos Aprovados!</h1><p style="margin: 0; font-size: 16px; opacity: 0.9;">Verificação concluída com sucesso</p></div><div style="background: #f9fafb; padding: 25px; border-radius: 10px; margin-bottom: 20px;"><p style="margin: 0 0 15px 0;">Seus documentos foram verificados e aprovados com sucesso!</p><p style="margin: 0;">Agora você tem acesso completo à plataforma FurionPay.</p></div><div style="text-align: center; padding: 20px;"><p style="color: #6b7280; font-size: 14px; margin: 0;">© 2024 FurionPay. Todos os direitos reservados.</p></div></body></html>', '["userEmail", "logoUrl"]'::jsonb),

('document_rejected', 'Documentos Rejeitados', '❌ Seus documentos precisam de atenção - FurionPay', '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="text-align: center; margin-bottom: 30px;"><img src="{logoUrl}" alt="FurionPay" style="max-width: 200px; height: auto;"></div><div style="background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px;"><h1 style="margin: 0 0 10px 0; font-size: 28px;">❌ Documentos Rejeitados</h1><p style="margin: 0; font-size: 16px; opacity: 0.9;">Ação necessária</p></div><div style="background: #f9fafb; padding: 25px; border-radius: 10px; margin-bottom: 20px;"><p style="margin: 0 0 15px 0;">Infelizmente, seus documentos não foram aprovados.</p><p style="margin: 0 0 15px 0;"><strong>Motivo:</strong> {reason}</p><p style="margin: 0;">Por favor, envie novos documentos para continuar o processo de verificação.</p></div><div style="text-align: center; padding: 20px;"><p style="color: #6b7280; font-size: 14px; margin: 0;">© 2024 FurionPay. Todos os direitos reservados.</p></div></body></html>', '["userEmail", "reason", "logoUrl"]'::jsonb),

('password_reset', 'Redefinição de Senha', '🔐 Código de redefinição de senha - FurionPay', '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="text-align: center; margin-bottom: 30px;"><img src="{logoUrl}" alt="FurionPay" style="max-width: 200px; height: auto;"></div><div style="background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px;"><h1 style="margin: 0 0 10px 0; font-size: 28px;">🔐 Redefinição de Senha</h1><p style="margin: 0; font-size: 16px; opacity: 0.9;">Use o código abaixo</p></div><div style="background: #f9fafb; padding: 25px; border-radius: 10px; margin-bottom: 20px; text-align: center;"><p style="margin: 0 0 20px 0;">Use o código abaixo para redefinir sua senha:</p><div style="background: #1f2937; color: #10b981; font-size: 32px; font-weight: bold; letter-spacing: 8px; padding: 20px; border-radius: 8px; font-family: monospace;">{code}</div><p style="margin: 20px 0 0 0; color: #6b7280; font-size: 14px;">Este código expira em 15 minutos.</p></div><div style="text-align: center; padding: 20px;"><p style="color: #6b7280; font-size: 14px; margin: 0;">© 2024 FurionPay. Todos os direitos reservados.</p></div></body></html>', '["code", "logoUrl"]'::jsonb),

('account_unlock', 'Desbloqueio de Conta', '🔓 Código de desbloqueio de conta - FurionPay', '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="text-align: center; margin-bottom: 30px;"><img src="{logoUrl}" alt="FurionPay" style="max-width: 200px; height: auto;"></div><div style="background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px;"><h1 style="margin: 0 0 10px 0; font-size: 28px;">🔓 Desbloqueio de Conta</h1><p style="margin: 0; font-size: 16px; opacity: 0.9;">Sua conta foi bloqueada temporariamente</p></div><div style="background: #f9fafb; padding: 25px; border-radius: 10px; margin-bottom: 20px; text-align: center;"><p style="margin: 0 0 15px 0;">Detectamos várias tentativas de login malsucedidas para o email <strong>{email}</strong>.</p><p style="margin: 0 0 20px 0;">Use o código abaixo para desbloquear sua conta:</p><div style="background: #1f2937; color: #f59e0b; font-size: 32px; font-weight: bold; letter-spacing: 8px; padding: 20px; border-radius: 8px; font-family: monospace;">{code}</div><p style="margin: 20px 0 0 0; color: #6b7280; font-size: 14px;">Este código expira em 15 minutos.</p></div><div style="text-align: center; padding: 20px;"><p style="color: #6b7280; font-size: 14px; margin: 0;">© 2024 FurionPay. Todos os direitos reservados.</p></div></body></html>', '["code", "email", "logoUrl"]'::jsonb),

('withdrawal_approved', 'Saque Aprovado', '💰 Seu saque foi aprovado - FurionPay', '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="text-align: center; margin-bottom: 30px;"><img src="{logoUrl}" alt="FurionPay" style="max-width: 200px; height: auto;"></div><div style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px;"><h1 style="margin: 0 0 10px 0; font-size: 28px;">💰 Saque Aprovado!</h1><p style="margin: 0; font-size: 16px; opacity: 0.9;">Seu dinheiro está a caminho</p></div><div style="background: #f9fafb; padding: 25px; border-radius: 10px; margin-bottom: 20px;"><p style="margin: 0 0 15px 0;">Seu saque foi aprovado com sucesso!</p><div style="background: white; padding: 15px; border-radius: 8px; border: 1px solid #e5e7eb;"><p style="margin: 0 0 10px 0;"><strong>Valor:</strong> R$ {amount}</p><p style="margin: 0 0 10px 0;"><strong>Banco:</strong> {bankName}</p><p style="margin: 0;"><strong>Chave PIX:</strong> {pixKey}</p></div><p style="margin: 15px 0 0 0; color: #6b7280; font-size: 14px;">O valor será creditado em sua conta em até 24 horas úteis.</p></div><div style="text-align: center; padding: 20px;"><p style="color: #6b7280; font-size: 14px; margin: 0;">© 2024 FurionPay. Todos os direitos reservados.</p></div></body></html>', '["amount", "bankName", "pixKey", "logoUrl"]'::jsonb),

('withdrawal_rejected', 'Saque Rejeitado', '❌ Seu saque foi rejeitado - FurionPay', '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="text-align: center; margin-bottom: 30px;"><img src="{logoUrl}" alt="FurionPay" style="max-width: 200px; height: auto;"></div><div style="background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px;"><h1 style="margin: 0 0 10px 0; font-size: 28px;">❌ Saque Rejeitado</h1><p style="margin: 0; font-size: 16px; opacity: 0.9;">Não foi possível processar seu saque</p></div><div style="background: #f9fafb; padding: 25px; border-radius: 10px; margin-bottom: 20px;"><p style="margin: 0 0 15px 0;">Infelizmente, seu saque foi rejeitado.</p><div style="background: white; padding: 15px; border-radius: 8px; border: 1px solid #e5e7eb; margin-bottom: 15px;"><p style="margin: 0 0 10px 0;"><strong>Valor:</strong> R$ {amount}</p><p style="margin: 0 0 10px 0;"><strong>Banco:</strong> {bankName}</p><p style="margin: 0;"><strong>Chave PIX:</strong> {pixKey}</p></div><div style="background: #fef2f2; padding: 15px; border-radius: 8px; border: 1px solid #fecaca;"><p style="margin: 0; color: #dc2626;"><strong>Motivo:</strong> {reason}</p></div><p style="margin: 15px 0 0 0; color: #6b7280; font-size: 14px;">O valor foi devolvido ao seu saldo disponível.</p></div><div style="text-align: center; padding: 20px;"><p style="color: #6b7280; font-size: 14px; margin: 0;">© 2024 FurionPay. Todos os direitos reservados.</p></div></body></html>', '["amount", "bankName", "pixKey", "reason", "logoUrl"]'::jsonb);

-- Create trigger for updated_at
CREATE TRIGGER update_email_templates_updated_at
BEFORE UPDATE ON public.email_templates
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();