-- Fix get_public_checkout_config return type mismatch (discount_popup_percentage is numeric in table)
DROP FUNCTION IF EXISTS public.get_public_checkout_config(uuid);

CREATE OR REPLACE FUNCTION public.get_public_checkout_config(p_product_id uuid)
RETURNS TABLE(
  id uuid,
  product_id uuid,
  user_id uuid,
  template text,
  template_id uuid,
  primary_color text,
  background_color text,
  show_countdown boolean,
  countdown_minutes integer,
  countdown_color text,
  countdown_text text,
  show_banners boolean,
  show_notifications boolean,
  show_security_badges boolean,
  show_product_image boolean,
  require_phone boolean,
  require_cpf boolean,
  require_birthdate boolean,
  require_address boolean,
  require_email_confirmation boolean,
  custom_button_text text,
  checkout_title text,
  checkout_subtitle text,
  buyer_section_title text,
  payment_section_title text,
  security_badge_text text,
  delivery_description text,
  footer_text text,
  header_logo_url text,
  thank_you_url text,
  back_redirect_url text,
  show_video boolean,
  video_url text,
  video_poster_url text,
  video_play_overlay_url text,
  show_whatsapp_button boolean,
  whatsapp_number text,
  show_discount_popup boolean,
  discount_popup_title text,
  discount_popup_message text,
  discount_popup_percentage numeric,
  discount_popup_cta text,
  discount_popup_color text,
  discount_popup_image_url text,
  selected_pixel_ids text[],
  product_pixels jsonb
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    pcc.id,
    pcc.product_id,
    pcc.user_id,
    pcc.template,
    pcc.template_id,
    pcc.primary_color,
    pcc.background_color,
    pcc.show_countdown,
    pcc.countdown_minutes,
    pcc.countdown_color,
    pcc.countdown_text,
    pcc.show_banners,
    pcc.show_notifications,
    pcc.show_security_badges,
    pcc.show_product_image,
    pcc.require_phone,
    pcc.require_cpf,
    pcc.require_birthdate,
    pcc.require_address,
    pcc.require_email_confirmation,
    pcc.custom_button_text,
    pcc.checkout_title,
    pcc.checkout_subtitle,
    pcc.buyer_section_title,
    pcc.payment_section_title,
    pcc.security_badge_text,
    pcc.delivery_description,
    pcc.footer_text,
    pcc.header_logo_url,
    pcc.thank_you_url,
    pcc.back_redirect_url,
    pcc.show_video,
    pcc.video_url,
    pcc.video_poster_url,
    pcc.video_play_overlay_url,
    pcc.show_whatsapp_button,
    pcc.whatsapp_number,
    pcc.show_discount_popup,
    pcc.discount_popup_title,
    pcc.discount_popup_message,
    pcc.discount_popup_percentage,
    pcc.discount_popup_cta,
    pcc.discount_popup_color,
    pcc.discount_popup_image_url,
    pcc.selected_pixel_ids,
    pcc.product_pixels
  FROM public.product_checkout_configs pcc
  WHERE pcc.product_id = p_product_id;
END;
$$;